name: API Documentation

on:
  push:
    paths:
      - 'api/**'
      - 'server/api/**' 
      - 'routes/**'
      - 'endpoints/**'
  pull_request:
    paths:
      - 'api/**'
      - 'server/api/**'
      - 'routes/**'
      - 'endpoints/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need at least 2 commits for git diff

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

       - run: npm install
       - run: npm install ai @ai-sdk/openai @octokit/rest

      - name: Configure Git
        run: |
          git config user.name "API Doc Bot"
          git config user.email "docs@github.com"

      - name: Generate API documentation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node ci-doc-writer.js

