name: API Documentation

on:
  push:
    paths:
      - 'api/**'
      - 'server/api/**' 
      - 'routes/**'
      - 'endpoints/**'
  pull_request:
    paths:
      - 'api/**'
      - 'server/api/**'
      - 'routes/**'
      - 'endpoints/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need at least 2 commits for git diff

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install
      - run: npm install ai @ai-sdk/openai

      - name: Configure Git
        run: |
          git config user.name "API Doc Bot"
          git config user.email "docs@github.com"

      - name: Generate API documentation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node -e "
          import('./api-doc-generator.js').then(module => {
            const generator = new module.APIDocumentationGenerator();
            return generator.generateAPIDocs();
          }).catch(console.error);
        "

      - name: Commit documentation updates
        run: |
          git add docs/
          if ! git diff --staged --quiet; then
            git commit -m "📚 Update API documentation"
            git push
          else
            echo "No documentation changes to commit"
          fi