name: Auto Bug Fix

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install
      - run: npm install ai @ai-sdk/openai

      - name: Configure Git
        run: |
          git config user.name "Auto Bug Fixer"
          git config user.email "action@github.com"

      - name: Run bug fixer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ci-bug-fixer.js