name: API Documentation

on:
  pull_request:
    paths:
      - 'lesson-8-api-docs-automation/api/**'
      - 'lesson-8-api-docs-automation/server/api/**' 
      - 'lesson-8-api-docs-automation/routes/**'
      - 'lesson-8-api-docs-automation/endpoints/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    defaults:
      run:
        working-directory: lesson-8-api-docs-automation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need at least 2 commits for git diff
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - name: Configure Git
        run: |
          git config user.name "API Doc Bot"
          git config user.email "docs@github.com"

      - name: Generate API documentation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node ci-doc-writer.js

